services:
    saml.attribute.displayName:
        class: Surfnet\SamlBundle\SAML2\Attribute\AttributeDefinition
        arguments:
            - displayName
            - 'urn:mace:dir:attribute-def:displayName'
            - 'urn:oid:2.16.840.1.113730.3.1.241'
        tags:
            - { name: 'saml.attribute' }

    saml.attribute.eduPersonTargetedID:
        class: Surfnet\SamlBundle\SAML2\Attribute\AttributeDefinition
        arguments:
            - eduPersonTargetedId
            - 'urn:mace:dir:attribute-def:eduPersonTargetedID'
            - 'urn:oid:1.3.6.1.4.1.5923.1.1.1.10'
        tags:
            - { name: 'saml.attribute' }

    saml.attribute.email:
        class: Surfnet\SamlBundle\SAML2\Attribute\AttributeDefinition
        arguments:
            - email
            - 'urn:mace:dir:attribute-def:email'
            - 'urn:oid:1.2.840.113549.1.9.1'
        tags:
            - { name: 'saml.attribute' }

    saml.attribute.schacHomeOrganization:
        class: Surfnet\SamlBundle\SAML2\Attribute\AttributeDefinition
        arguments:
            - schacHomeOrganization
            - 'urn:mace:terena.org:attribute-def:schacHomeOrganization'
            - 'urn:oid:1.3.6.1.4.1.25178.1.2.9'
        tags:
            - { name: 'saml.attribute' }
